# Please see DEVELOPERS.md for help
#
# Contributions to this file are welcome but please note that this file is
# minimal by design, with the idea to make it easily extensible via
# docker-compose.override.yml. For help with doing that, please see
# DEVELOPERS.md
services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: 'academy_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'wikipass'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./db_data:/var/lib/mysql

  mediawiki:
    image: docker-registry.wikimedia.org/dev/bookworm-php83-fpm:1.0.0
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    volumes:
      - ./:/var/www/html:cached
    env_file:
      - '.env'
    environment:
      COMPOSER_CACHE_DIR: '/var/www/html/cache/composer'
      MW_SERVER: 'http://localhost:${MW_DOCKER_PORT:-8080}'
      MW_DOCKER_PORT: "${MW_DOCKER_PORT:-8080}"
      MW_SCRIPT_PATH: ''
      MW_DBTYPE: 'mysql'
      MW_DBHOST: 'db'
      MW_DBNAME: 'academy_wiki'
      MW_DBUSER: 'wikiuser'
      MW_DBPASS: 'wikipass'
      MW_LANG: 'en'
      MW_USER: '${MEDIAWIKI_USER:-Admin}'
      MW_PASS: '${MEDIAWIKI_PASSWORD:-dockerpass}'
      MW_SITENAME: 'MediaWiki'
      MW_LOG_DIR: /var/www/html/cache
      XDEBUG_CONFIG: '${XDEBUG_CONFIG}'
      XDEBUG_ENABLE: '${XDEBUG_ENABLE:-true}'
      XHPROF_ENABLE: '${XHPROF_ENABLE:-true}'
    depends_on:
      - db

  mediawiki-web:
    image: docker-registry.wikimedia.org/dev/bookworm-apache2:1.0.1
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    ports:
      - "${MW_DOCKER_PORT:-8080}:8080"
    volumes:
      - ./:/var/www/html:cached
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    env_file:
      - '.env'
    environment:
      MW_LOG_DIR: /var/www/html/cache
      MW_DOCKER_PORT: "${MW_DOCKER_PORT:-8080}"

  mediawiki-jobrunner:
    image: docker-registry.wikimedia.org/dev/bookworm-php83-jobrunner:1.0.0
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    volumes:
      - ./:/var/www/html:cached
    env_file:
      - '.env'
    environment:
      MW_LOG_DIR: /var/www/html/cache
      MW_INSTALL_PATH: /var/www/html
